import sys
import os

cl_defines = []
for key, value in ARGLIST:
	if key == 'define':
		cl_defines.append(value)

# Detect Python version automatically
python_ver = f"{sys.version_info.major}.{sys.version_info.minor}"
python_version_decimal = sys.version_info.major * 10 + sys.version_info.minor

# Validate Python version (require 3.9+)
if python_version_decimal < 39:
    raise RuntimeError(f"Python 3.9+ required, but found {python_ver}. Please upgrade Python.")

# Detect BLAS/LAPACK libraries
# Priority: Intel MKL > OpenBLAS > system LAPACK
lapack_libs = []
lapack_include = []
lapack_libpath = []

# Check for Intel MKL
mkl_root = os.environ.get('MKLROOT', '')
if mkl_root and os.path.exists(mkl_root):
    print(f"Using Intel MKL from: {mkl_root}")
    lapack_libs = ['mkl_core', 'mkl_intel_thread', 'mkl_sequential', 'iomp5']
    lapack_libpath = [os.path.join(mkl_root, 'lib', 'intel64')]
    lapack_include = [os.path.join(mkl_root, 'include')]
    cl_defines.append('USE_INTEL_MKL')
else:
    # Check for OpenBLAS
    if os.path.exists('/usr/lib/x86_64-linux-gnu/libopenblas.so') or \
       os.path.exists('/usr/lib64/libopenblas.so'):
        print("Using OpenBLAS")
        lapack_libs = ['openblas', 'lapack', 'blas']
        cl_defines.append('USE_OPENBLAS')
    else:
        # Fall back to system LAPACK
        print("Using system LAPACK/BLAS")
        lapack_libs = ['lapack', 'blas']

env = Environment(
	CPPDEFINES = cl_defines,
	CPPPATH = ['tnt_126', 'geo_bsd/hpgl'] + lapack_include,
	LIBS = ['stdc++', 'libgomp', 'pthread'] + lapack_libs,
	LIBPATH = lapack_libpath,
)

dbg_suffixes = {True: '_d', False: ''}
py_pkg_suffixes = {True: '-dbg', False: ''}
ccflags = {True: '-ggdb -fPIC',
	   False: '-ggdb -fPIC -O2 -finline-functions -fmove-loop-invariants -fopenmp -funroll-loops -march=native -msse -msse2 -mfpmath=sse -Wall -Wno-missing-braces -Wno-sign-compare '}

cppdefines = {True: ['DEBUG'],
	      False: ['NDEBUG']}

dir1 = {True: 'debug', False:'release'}

for debug in [False, True]:
	env2 = env.Clone(
		DBG_SUFFIX = dbg_suffixes[debug],
		CONFIG_NAME = dir1[debug],
		CCFLAGS = ccflags[debug],
		TEMPDIR1 = 'temp/${CONFIG_NAME}',
		PY_PKG_DIR = 'out/$CONFIG_NAME',
		SHLIBPREFIX = '')

	env2.Append(CPPDEFINES = cppdefines[debug])
	env2['BUILDROOT'] = '$TEMPDIR1'
	env2.VariantDir('$BUILDROOT/geo_bsd', 'geo_bsd', duplicate=0)
	hpgl_src = env2.Glob('$BUILDROOT/geo_bsd/hpgl/*.cpp')
	env2.SharedLibrary('geo_bsd/hpgl${DBG_SUFFIX}', hpgl_src)
	env2.SharedLibrary('geo_bsd/_cvariogram${DBG_SUFFIX}',
			env2.Glob('$BUILDROOT/geo_bsd/_cvariogram/*.cpp'))


Default(['geo_bsd'])


